[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
vibestamp = "2Y171N7NVjqtjguLHrNwXfA5w7yHW4hkJAbNySBw7pmQ"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
